"""Generate endpoint schemas for travel plan generation and retrieval."""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, field_validator
from app.schemas.search import SearchResultItem


class Destination(BaseModel):
    """Destination information in travel plan."""

    name: str = Field(..., description="Destination name", example="Paris, France")
    description: str = Field(..., description="Brief overview of destination")
    recommended_duration_days: int = Field(..., description="Suggested duration of stay in days", example=3)


class Attraction(BaseModel):
    """Recommended attraction or point of interest."""

    name: str = Field(..., description="Attraction name", example="Eiffel Tower")
    destination: str = Field(..., description="City or region where attraction is located")
    category: str = Field(..., description="Category (e.g., Landmark, Museum, Park, Dining)")
    description: str = Field(..., description="Brief description and visit tips")
    estimated_duration_hours: Optional[float] = Field(default=None, description="Recommended visit duration in hours")


class Hotel(BaseModel):
    """Recommended accommodation or hotel."""

    name: str = Field(..., description="Hotel or property name", example="Le Meurice")
    destination: str = Field(..., description="Location / city")
    tier: str = Field(..., description="Price/quality tier (e.g. Budget, Mid-Range, Luxury)")
    description: str = Field(..., description="Property description and highlights")
    estimated_nightly_rate: Optional[str] = Field(default=None, description="Estimated price per night", example="$250/night")


class TimeSlot(BaseModel):
    """A single scheduled activity at a specific time of day."""

    activity: str = Field(..., description="What to do at this time", example="Morning walk")


class DaySchedule(BaseModel):
    """Daily itinerary schedule item, keyed by clock time."""

    day: str = Field(..., description="Day number", example="1")
    title: Optional[str] = Field(default=None, description="Focus or title for the day", example="Historic Center & Seine Cruise")
    time: Dict[str, TimeSlot] = Field(
        ...,
        description="Activities keyed by time of day, in chronological order",
        example={"8:00 AM": {"activity": "Morning walk"}, "10:00 AM": {"activity": "Visit the Louvre"}},
    )

    @field_validator("day", mode="before")
    @classmethod
    def coerce_day_to_str(cls, v: Any) -> Any:
        # LLMs often emit "day": 1 even when shown "1"; accept either.
        return str(v) if isinstance(v, int) else v


class BudgetBreakdown(BaseModel):
    """Estimated trip budget breakdown."""

    currency: str = Field(default="USD", description="Currency symbol/code")
    accommodation_est: str = Field(..., description="Estimated accommodation cost", example="$600")
    activities_est: str = Field(..., description="Estimated activities/tours cost", example="$200")
    food_dining_est: str = Field(..., description="Estimated meals & dining cost", example="$300")
    total_estimated: str = Field(..., description="Total estimated trip cost", example="$1,100")


class TravelPlan(BaseModel):
    """Structured travel plan generated by the AI engine."""

    title: str = Field(..., description="Title of the travel itinerary", example="5-Day Paris Highlights Itinerary")
    summary: str = Field(..., description="Executive summary and trip overview")
    destinations: List[Destination] = Field(default_factory=list, description="Target destinations")
    attractions: List[Attraction] = Field(default_factory=list, description="Key attractions")
    hotels: List[Hotel] = Field(default_factory=list, description="Recommended accommodations")
    daily_schedule: List[DaySchedule] = Field(default_factory=list, description="Day-by-day itinerary schedule")
    budget: BudgetBreakdown = Field(..., description="Trip budget breakdown")
    travel_tips: List[str] = Field(default_factory=list, description="Practical travel tips and local recommendations")


class GenerateRequest(BaseModel):
    """Incoming request to the LLM generation endpoint."""

    request_id: Optional[str] = Field(
        default=None,
        description="Optional caller-supplied request correlation ID. If omitted, one will be generated.",
        example="req_12345",
    )
    prompt: str = Field(
        ...,
        description="Prompt or query describing the plan or task required",
        example="Create a 5-day travel itinerary for Paris with luxury hotels and top sights",
    )
    metadata: Optional[Dict[str, Any]] = Field(
        default_factory=dict,
        description="Arbitrary context or configuration metadata",
        example={"source": "admin_panel", "priority": "high"},
    )

    @field_validator("prompt")
    @classmethod
    def validate_prompt_not_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Prompt must be a non-empty string")
        return v.strip()

    @field_validator("request_id")
    @classmethod
    def validate_request_id(cls, v: Optional[str]) -> Optional[str]:
        if v is not None:
            v_clean = v.strip()
            if not v_clean:
                raise ValueError("request_id cannot be an empty string if provided")
            return v_clean
        return v


class GenerateResponse(BaseModel):
    """Output from the generate workflow indicating retrieval result and optional generated TravelPlan."""

    success: bool = Field(default=True, description="Indicates successful execution of the workflow")
    request_id: str = Field(..., description="Correlated request ID", example="req_12345")
    status: str = Field(
        ...,
        description="'data_found' when plan generated, 'data_required' when scraper needed, or 'generation_failed' when LLM parse failed",
        example="data_found",
    )
    data_found: bool = Field(..., description="True if Qdrant returned relevant knowledge")
    data_required: bool = Field(..., description="True if Admin must trigger scraper/store pipeline")
    results: List[SearchResultItem] = Field(
        default_factory=list,
        description="Retrieved vector items when data is found",
    )
    plan: Optional[TravelPlan] = Field(
        default=None,
        description="Structured travel plan produced by LLM when data is found and generation succeeds",
    )
    message: str = Field(..., description="Summary explanation of the result")
    metadata: Optional[Dict[str, Any]] = Field(
        default_factory=dict,
        description="Echoed or augmented metadata",
    )
